# Task: Quantum Circuit Simulator

The goal here is to implement simple quantum circuit simulator.

## Introduction

Before we start coding:


### Qubit

Qubit is the basic unit of quantum information. It is a two-state (or two-level) quantum-mechanical system, and can be represented by a linear superposition of its two orthonormal basis states (or basis vectors). The vector representation of a single qubit is: ${\vert a\rangle =v_{0} \vert 0\rangle +v_{1} \vert 1\rangle \rightarrow {\begin{bmatrix}v_{0}\\v_{1}\end{bmatrix}}}$,
Here, ${\displaystyle v_{0}}v_{0}$ and ${\displaystyle v_{1}}v_{1}$ are the complex probability amplitudes of the qubit. These values determine the probability of measuring a 0 or a 1, when measuring the state of the qubit.

Code:

In [1]:
# Qubit in |0> state (100% probability of measuring 0)
q0 = [1, 0]

# Qubit in |1> state (100% probability of measuring 1)
q1 = [0, 1] 

# Qubit |+> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1)
q2 = [0.7071067811865475, 0.7071067811865475]

# Qubit |-> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1) with phase pi
q3 = [0.7071067811865475, -0.7071067811865475]

# Qubit |i> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1) with phase pi/2
q3 = [0.7071067811865475, 0+0.7071067811865475j]

# Qubit |-i> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1) with phase -pi/2
q4 = [0.7071067811865475, 0-0.7071067811865475j]


Note that vector contains probability amplitudes - not probabilities. Probability amplitude is complex number and can be negative. Probability is calculated as absolute value squared:

In [2]:
import numpy as np

q4 = np.array([0.7071067811865475+0j, 0-0.7071067811865475j])
p4 = np.abs(q4)**2
print(p4)


[0.5 0.5]


### State vector

The combined state of multiple qubits is the tensor product of their states (vectors). The tensor product is denoted by the symbol ${\displaystyle \otimes }$.

The vector representation of two qubits is:

${\displaystyle \vert ab\rangle =\vert a\rangle \otimes \vert b\rangle =v_{00}\vert 00\rangle +v_{01}\vert 01\rangle +v_{10}\vert 10\rangle +v_{11}\vert 11\rangle \rightarrow {\begin{bmatrix}v_{00}\\v_{01}\\v_{10}\\v_{11}\end{bmatrix}}}$

Example:

In [3]:
# Qubit in |0> state (100% probability of measuring 0)
q0 = [1, 0]

# Qubit in |1> state (100% probability of measuring 1)
q1 = [0, 1] 

combined_state = np.kron(q0, q1)

print(combined_state)

[0 1 0 0]


Now, what this vector tells us?

It will be more clear if we write vector elements in a column with index expressed in binary format:

```
Index (dec)  Index (bin)  Amplitude  Probability
================================================
0            00           0          0 (  0%)
1            01           1          1 (100%)
2            10           0          0 (  0%)
3            11           0          0 (  0%)
```

- First element (binary: 00) is probability of measuring 0 on both qubits.
- Second element (binary: 01) is probability of measuring 0 on first qubit and 1 on second qubit.
- Third element (binary: 10) is probability of measuring 1 on first qubit and 0 on second qubit.
- Fourth element (binary: 11) is probability of measuring 1 on both qubits.

#### Endianness

It is important to say that different quantum programming frameworks use different orientation of bitstrings (endianness). In previous example, left bit belongs to first qubit and righ bit belongs to second qubit. This enconding is called "big endian".

But, in some frameworks (like Qiskit), encoding is opposite: rightmost bit belongs to first qubit and leftmost bit belongs to last qubit. This is called "little endian".

So, vector from our example in Qiskit's "little endian" encoding will look like this:

```
Index (dec)  Index (bin)  Amplitude  Probability
================================================
0            00           0          0 (  0%)
1            01           0          0 (  0%)
2            10           1          1 (100%)
3            11           0          0 (  0%)
```

"Little endian" encoding:

- First element (binary: 00) is probability of measuring 0 on both qubits.
- Second element (binary: 01) is probability of measuring 0 on second qubit and 1 on first qubit.
- Third element (binary: 10) is probability of measuring 1 on second qubit and 0 on first qubit.
- Fourth element (binary: 11) is probability of measuring 1 on both qubits.


# Quantum gates

Quantum gates are basic units of quantum processing. Gates are represented as unitary matrices. The action of the gate on a specific quantum state is found by multiplying the vector ${\displaystyle \vert \psi _{1}\rangle }$  which represents the state, by the matrix ${\displaystyle U}$ representing the gate. The result is a new quantum state ${\displaystyle \vert \psi _{2}\rangle }$ 

${\displaystyle U\vert \psi _{1}\rangle =\vert \psi _{2}\rangle }$

Quantum gates (usually) act on small number of qubits. We have single-qubit and multi-qubit gates. n-qubit gate is represented as $2^n\times2^n$ unitary matrix.

Examples:

#### Single qubit gates

X (aka NOT) gate:

$X = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$

Hadamard gate:

$H = \tfrac{1}{\sqrt{2}}\begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}$

General single qubit rotation gate:

$U_3(\theta, \phi, \lambda) = \begin{bmatrix} \cos(\theta/2) & -e^{i\lambda}\sin(\theta/2) \\
            e^{i\phi}\sin(\theta/2) & e^{i\lambda+i\phi}\cos(\theta/2)
     \end{bmatrix}$

#### Two-qubit gates:

Controlled-X (aka CNOT) gate:

${CNOT} = \begin{bmatrix} 1 & 0 & 0 & 0 \\
                         0 & 1 & 0 & 0 \\
                         0 & 0 & 0 & 1 \\
                         0 & 0 & 1 & 0 \\
         \end{bmatrix}$

SWAP gate:

${SWAP} = \begin{bmatrix} 1 & 0 & 0 & 0 \\
                         0 & 0 & 1 & 0 \\
                         0 & 1 & 0 & 0 \\
                         0 & 0 & 0 & 1 \\
         \end{bmatrix}$

#### Examples

Let's see how single-qubit gate modifies state of the qubit:

In [4]:
import numpy as np

# Let's start with qubit in state |0> (100% probability of measuring 0)   

q0 = np.array([1, 0])

print("Initial state:\t", q0)

# Define X (NOT) gate:

X = np.array([
[0, 1],
[1, 0]
])

# Now apply X gate to a qubit (matrix-vector dot product):

q0 = np.dot(X, q0)

print("Final state:\t", q0)


Initial state:	 [1 0]
Final state:	 [0 1]


After applying X gate, qubit flips from state $|0\rangle$ to state $|1\rangle$.

Now, let's see how Hadamard gate works:

In [5]:
import numpy as np

# Let's start with qubit in state |0> (100% probability of measuring 0)
    
q0 = np.array([1, 0])

print("Initial state:\t", q0)

# Define H (Hadamard) gate:

H = np.array([
[1/np.sqrt(2), 1/np.sqrt(2)],
[1/np.sqrt(2), -1/np.sqrt(2)]
])

# Now apply H gate to a qubit (matrix-vector dot product):

q0 = np.dot(H, q0)

print("Final state:\t", q0)


Initial state:	 [1 0]
Final state:	 [0.70710678 0.70710678]


After applying Hadamard gate on qubit in state $|0\rangle$ it evolves to state $|+\rangle$ which is equal superposition.

### Matrix operator

Quantum program eveloves quantum state by multiplying state vector with each gate's unitary matrix (dot product). Note that dimension of the state vector and dimension of the unitary matrix describing a gate usually don't match. For example: 3-qubit quantum circuit's state vector has $2^n=2^3=8$ elements, but single-qubit gate has $2^n\times2^n=2^1\times2^1=2\times2$ elements. In order to perform matrix-vector multiplication, we need to "resize" gate's matrix to the dimension of the state vector. Let's call that matrix a **matrix operator**.

Note that size of the matrix operator is $2^n\times2^n$ where $n$ is total number of qubits in the circuit, so storing it into memory and calculating it requires a lot of memory and cpu power for bigger circuits. Optimizing this code is most interesting and challenging part, but for our purpose it is enough if you make it work smoothly with 8 qubits (the more - the better).

#### Matrix operator for single-qubit gates

Matrix operator for single-qubit gate can be calculated by performing tensor product of gate's unitary matrix and $2\times2$ identity matrices in correct order.

Example for single-qubit gate $U$ in 3-qubit circuit:

- gate on qubit 0: ${O=U \otimes I \otimes I}$
- gate on qubit 1: ${O=I \otimes U \otimes I}$
- gate on qubit 2: ${O=I \otimes I \otimes U}$

Example matrix operator for X gate acting on third qubit in 3-qubit circuit can be calculated like this:

In [6]:
import numpy as np

# Let's define state vector of the 3-qubit circuit in "ground state" (all qubits in state |0>)

psi = [1, 0, 0, 0, 0, 0, 0, 0]
print("Initial state:", psi)


# Define X (NOT) gate:

X = np.array([
[0, 1],
[1, 0]
])

# Define 2x2 identity

I = np.identity(2)

# Calculate operator for X gate acting on third qubit in 3-qubit circuit

O = np.kron(np.kron(I, I), X)

print("\nOperator:\n\n", O, "\n")


# And finally, apply operator

psi = np.dot(psi, O)
print("Final state:", psi)


Initial state: [1, 0, 0, 0, 0, 0, 0, 0]

Operator:

 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]] 

Final state: [0. 1. 0. 0. 0. 0. 0. 0.]


We are dealing with "big endian" encoding, so this result is correct: third qubit is flipped to state $|1\rangle$  and other qubits are not changed.

**Note**: if we want vector in "little endian" encoding (like Qiskit), then order in which we perform tensor product to calculate operator is opposite. Instead ${O=I \otimes I \otimes U}$ we would do ${O=U \otimes I \otimes I}$.

#### Matrix operator for multi-qubit gates

If we want to apply two qubit gate on subsequent qubits ( 0-1, 1-2, 2-3 etc.) then we can use the same technique like we do with single qubit gates:

For 3-qubit circuit, CNOT gate:

- acting on first and second qubit, operator is ${O=CNOT \otimes I}$

- acting on second and third qubit, operator is ${O=I \otimes CNOT}$

But, multi-qubit gates can be applied to qubits which are not consequent, so this is not that trivial.

The main feature of a controlled-$U$ operation, for any unitary $U$, is that it (coherently) performs an operation on some qubits depending on the value of some single qubit. The way that we can write this explicitly algebraically (with the control on the first qubit) is:

$\mathit{CU} \;=\; \vert{0}\rangle\!\langle{0}\vert \!\otimes\! \mathbf 1 \,+\, \vert{1}\rangle\!\langle{1}\vert \!\otimes\! U$

where ${\mathbf 1}$ is an identity matrix of the same dimension as $U$. Here, ${\ket{0}\!\bra{0}}$ and ${\ket{1}\!\bra{1}}$ are projectors onto the states ${\ket{0}}$ and ${\ket{1}}$ of the control qubit &mdash; but we are not using them here as elements of a measurement, but to describe the effect on the other qubits depending on one or the other subspace of the state-space of the first qubit.

We can use this to derive the matrix for the gate ${\mathit{CX}_{1,3}}$ which performs an $X$ operation on qubit 3, coherently conditioned on the state of qubit 1, by thinking of this as a controlled-${(\mathbf 1_2 \!\otimes\! X)}$ operation on qubits 2 and 3:

$\begin{aligned}
\mathit{CX}_{1,3} \;&=\;
\vert{0}\rangle\!\langle{0}\vert \otimes \mathbf 1_4 \,+\, \vert{1}\rangle\!\langle{1}\vert \otimes (\mathbf 1_2 \otimes X)
\\[1ex]&=\;
\begin{bmatrix}
  \mathbf 1_4 & \mathbf 0_4  \\
  \mathbf 0_4 & (\mathbf 1_2 \!\otimes\! X) 
\end{bmatrix}
\;=\;
\begin{bmatrix}
  \mathbf 1_2 & \mathbf 0_2 & \mathbf 0_2 & \mathbf 0_2 \\
  \mathbf 0_2 & \mathbf 1_2 & \mathbf 0_2 & \mathbf 0_2 \\
  \mathbf 0_2 & \mathbf 0_2 & X & \mathbf 0_2 \\
  \mathbf 0_2 & \mathbf 0_2 & \mathbf 0_2 & X
\end{bmatrix},
\end{aligned}$

where the latter two are block matrix representations to save on space (and sanity).

Better still: we can recognise that &mdash; on some mathematical level where we allow ourselves to realise that the order of the tensor factors doesn't have to be in some fixed order &mdash; the control and the target of the operation can be on any two tensor factors, and that we can fill in the description of the operator on all of the other qubits with $\mathbf 1_2$. This would allow us to jump straight to the representation

$\begin{aligned}
\mathit{CX}_{1,3} \;&=&\;
\underbrace{\vert{0}\rangle\!\langle{0}\vert}_{\text{control}} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{uninvolved}\!\!\!\!} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{target}\!\!\!\!}
&+\,
\underbrace{\vert{1}\rangle\!\langle{1}\vert}_{\text{control}} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{uninvolved}\!\!\!\!} \otimes \underbrace{\; X\;}_{\!\!\!\!\text{target}\!\!\!\!}
\\[1ex]&=&\;
\begin{bmatrix}
  \mathbf 1_2 & \mathbf 0_2 & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} \\
  \mathbf 0_2 & \mathbf 1_2 & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2}
\end{bmatrix}
\,&+\,
\begin{bmatrix}
  \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & X & \mathbf 0_2 \\
  \phantom{\mathbf 0_2} & \phantom{\mathbf 0_2} & {\mathbf 0_2} & X
\end{bmatrix}
\end{aligned}$

and also allows us to immediately see what to do if the roles of control and target are reversed:

$\begin{aligned}
\mathit{CX}_{3,1} \;&=&\;
\underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{target}\!\!\!\!} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{uninvolved}\!\!\!\!} \otimes \underbrace{\vert{0}\rangle\!\langle{0}\vert}_{\text{control}}
\,&+\,
\underbrace{\;X\;}_{\!\!\!\!\text{target}\!\!\!\!} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{uninvolved}\!\!\!\!} \otimes \underbrace{\vert{1}\rangle\!\langle{1}\vert}_{\text{control}}
\\[1ex]&=&\;
{\scriptstyle\begin{bmatrix}
 \!\vert{0}\rangle\!\langle{0}\vert\!\! & & & \\
 & \!\!\vert{0}\rangle\!\langle{0}\vert\!\! & & \\
& & \!\!\vert{0}\rangle\!\langle{0}\vert\!\! & \\
& & & \!\!\vert{0}\rangle\!\langle{0}\vert
\end{bmatrix}}
\,&+\,
{\scriptstyle\begin{bmatrix}
 & & \!\!\vert{1}\rangle\!\langle{1}\vert\!\! & \\
 & & & \!\!\vert{1}\rangle\!\langle{1}\vert \\
\!\vert{1}\rangle\!\langle{1}\vert\!\! & & &  \\
& \!\!\vert{1}\rangle\!\langle{1}\vert & &
\end{bmatrix}}
\\[1ex]&=&\;
\left[{\scriptstyle\begin{matrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1
\end{matrix}}\right.\,\,&\,\,\left.{\scriptstyle\begin{matrix}
0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0
\end{matrix}}\right].
\end{aligned}$

But best of all: if you can write down these operators algebraically, you can take the first steps towards dispensing with the giant matrices entirely, instead  reasoning about these operators algebraically using expressions such as $\mathit{CX}_{1,3} =
\vert{0}\rangle\!\langle{0}\vert \! \otimes\!\mathbf 1_2\! \otimes\! \mathbf 1_2 +
 \vert{1}\rangle\!\langle{1}\vert \! \otimes\!  \mathbf 1_2 \! \otimes\!  X$
and
$\mathit{CX}_{3,1} =
\mathbf 1_2 \! \otimes\! \mathbf 1_2 \! \otimes \! \vert{0}\rangle\!\langle{0}\vert +
X \! \otimes\! \mathbf 1_2 \! \otimes \! \vert{1}\rangle\!\langle{1}\vert$.


For Example, let's calculate operator for Controlled-X (CNOT) on first qubit as control and third qubit as target in 3 qubit quantum circuit:

In [7]:
import numpy as np

# Define X gate (CNOT is controlled-X):

X = np.array([
[0, 1],
[1, 0]
])

# Define 2x2 Identity

I = np.identity(2)


# Define projection operator |0><0|

P0x0 = np.array([
[1, 0],
[0, 0]
])

# Define projection operator |1><1|

P1x1 = np.array([
[0, 0],
[0, 1]
])

# And now calculate our operator:

O = np.kron(np.kron(P0x0, I), I) + np.kron(np.kron(P1x1, I), X)

print("CNOT(0, 2) for 3-qubit circuit, operator is:\n")
print(O)

O = (np.kron(P0x0, I)) + np.kron(P1x1, X)

CNOT(0, 2) for 3-qubit circuit, operator is:

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In order to implement simulator, it is best if you have function which returns operator for any unitary targeting any qubit(s) for any circuit size, something like:

```
get_operator(total_qubits, gate_unitary, target_qubits)
```

But this is not trivial so **it is enough if you can implement it for any 1-qubit gates and CNOT only.**

If you are still enthusiastic and you wish to implement universal operator function then please refer to:

- [qosf-simulator-task-additional-info.pdf](https://github.com/quantastica/qosf-mentorship/blob/master/qosf-simulator-task-additional-info.pdf)


- Book *Nielsen, Michael A.; Chuang, Isaac (2000). Quantum Computation and Quantum Information, 10th Anniversary Edition, Section 8.2.3, Operator-Sum Representation*

### Measurement

State vector of the real quantum computer cannot be directly observed. All we can read out of qubit is a single classical bit. So best we can get as output from quantum computer is bitstring of size $n$ where $n$ is number of qubits. Reading the state from a qubit is called "measurement". When qubit is in superposition, measurment puts qubit in one of two classical states. If we read 1 from qubit, it will "collapse" to state |1> and will stay there - superposition is "destroyed", and any subsequent measurement will return the same result.

Measurement is non-unitary operation on the state vector. But for simplicity, and because we can access state vector of our simulator, it is easier if we do it with a trick:

We can simulate measurement by choosing element from the state vector with weighted random function. Elements with larger probability amplitude will be returned more often, and elements with smaller probability amplitude will be returned less often. Elements with zero probability will never be returned.

For example, this state vector:

```
Index (dec)  Index (bin)  Amplitude   Probability
=================================================
0            00           0.70710678  0.5 (50%)
1            01           0           0   ( 0%)
2            10           0           0   ( 0%)
3            11           0.70710678  0.5 (50%)
```

Our random function should return elements 00 and 11 equaly often and never return 01 and 10. If we execute it 1000 times (1000 shots) we should get something like this:

```
{
  "00": 494,
  "11": 506
}
```
*(this is random, so it usually is not exactly 500/500 and that is completelly fine)*


## Requirements

It is expected that simulator can perform following:

- initialize state

- read program, and for each gate:
    - calculate matrix operator
    - apply operator (modify state)
    
- perform multi-shot measurement of all qubits using weighted random technique

It is up to you how you will organize code, but this is our suggestion:

### Input format (quantum program)

It is enough if simulator takes program in following format:

```
[
  { "unitary": [[0.70710678, 0.70710678], [0.70710678, -0.70710678]], "target": [0] }, 
  { "unitary": [ [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0] ], "target": [0, 1] }
  ...
]
```

Or, you can define unitaries in the code, and accept program with gate names instead:

```
[
  { "gate": "h", "target": [0] }, 
  { "gate": "cx", "target": [0, 1] }
  ...
]
```


### Simulator program

Not engraved into stone, but you can do something like this:

## Extra Files for the simulator task

For my simulator proposal I need some extra documents which I added in the notebook to handle in a general way the different processes and classes involved in the circuits, these are:

<ul>
<li>gates_basic.py</li>
<li>find_gate.py</li>
<li>gates_x.py</li>
<li>gates_h.py</li>
<li>gates_swap.py</li>
<li>operator_size.py</li>
</ul>

##### Note: those files were added in the notebook to make it more accessible to understand the project.


In [8]:
########### gates_basic.py  ######################
####  This static class is intended         ###### 
####  to define in methods the base         ###### 
####  matrices of size 2x2:                 ######
####  -projection of the operator |0><0|,   ######
####  -projection of the operator |1><1|,    ######
####  -the Identity,                        ######
####  -and U3(theta,phi,landa).             ######
##################################################

#### define the four method for the basic matrices of size 2x2
#### in the static class gates_basic
#### using import numpy as np library for the matrices
class gates_basic: 
    
    ### Define of the operator |0><0|
    def p0x0():
        return np.array([[1, 0],  ## return the matrix 
                         [0, 0]]) ## equals to |0><0|
    
    ### Define of the operator |0><0|
    def p1x1():
        return np.array([[0, 0],  ## return the matrix 
                         [0, 1]]) ## equals to |1><1|
    
    ## Define the Identity matriz of size 2x2
    def i():
        return np.array([[1, 0],  ## return the identity 
                         [0, 1]]) ## matrix of 2x2
    
    ## Define the U3 matriz of size 2x2
    ## This matrix needs three angles:
    ##  -theta
    ##  -lambda
    ##  -ph
    ## and works with complex numbers (0+1j = a+bi mathematic expresion) 
    ## in order to modify the qubits scalars values (alpha and beta)
    def u3(theta,lambda_,phi):
        return np.array([[np.cos(theta/2), -np.exp(0+1j * lambda_) * np.sin(theta / 2)],
                       [np.exp(0+1j * phi) * np.sin(theta / 2),
                        np.exp(0+1j * lambda_ + 0+1j * phi) * np.cos(theta / 2)]])
    
    ### this matrix it was define in the tutorial part of this notebook.
    


In [9]:
########### find_gate.py  ######################
####  It consists of a static class that  ###### 
####  has different methods to indicate   ###### 
####  in the case of using multiple       ######
####  qubits how to perform the tensor    ######
####  product for 2x2 and 4x4 gates       ######
####  with its different possibilities.   ######
################################################


#### define the method fwhen needs 
#### the product tensfor for  matrices of size 2x2;
#### when are using matrices of size 4x4 with tensor product
#### in the original and inverse matrix;
#### finally all the posibilities when use a matrix of size 4x4
#### using qubits moe than 2.
class find_gate:
    
    #### Define the method when is neccesary apply the tensor product
    #### in a matrix of size 2x2
    ### needs the number of qubits, the qubit to modify
    ### and the matrix of size 2x2.
    def gate_1xn(total_qubits,target,gate):
        operators = []                 ## using a list for every gate by qubit
        for j in range(total_qubits):  ## iteration on all the qubits
            if j ==  target:           ## when find the value for the qubit  
                operators.append(gate) ## to apply the gate we append in the list
            else:                      ## in other case we append the identity gate
                operators.append(gates_basic.i()) 
        O_state =  operators[0]        ## when finish the iterative for
        for j in range (1,len(operators)):  ## whe apply the tensor product   
            O_state = np.kron(operators[j],O_state) ## for all the gates o size 2x2
        return O_state                 ## return the matriz result of size 2**nẍ2**n
                                       ## where n = total_qubits

    #### The method of constructing a CU gate 
    #### by considering the U matriz of size 2x2, 
    #### the target qubit and the control qubit.
    #### when control qubit is less than target qubit 
    def gate_i_i2xn(target_0,target_1,gate): ## is neccesary two parts to build the gate
        left_part =  gates_basic.i()         ## left part is initialized with an identity gate
        right_part = gates_basic.i()         ## right part is initialized with an identity gate
                
        for j in range(target_0,target_1):   ## iterative function to find the gates
                                             ## between target and controls qubits positions
            if j == target_0:                ## when find the control qubit value
                left_part = np.kron(gates_basic.p0x0(),left_part)   ## apply the tensor product 
                right_part = np.kron(gates_basic.p1x1(),right_part) ## between left part and |0><0!
                                             ## and right_part with |1><1| and assign 
                                             ## in its respectively variable left_part or right part

            elif j == target_1-1:            ## When find the target qubit position we apply 
                left_part = np.kron(left_part,gates_basic.i()) ## product tensor between left and   
                right_part = np.kron(right_part,gate)          ## right part with  Identity and 
                                             ## U gate rrespectively
                    
            else:                            ## in other case apply on left_part and right_part
                left_part = np.kron(left_part,gates_basic.i())   ## the tensor product with 
                right_part = np.kron(right_part,gates_basic.i()) ## identities gate of size 2x2
        
        O_state = left_part + right_part ## finally, adder the left_part matrix with right_part matrix
        return O_state                   ## return the final matrix    
    
    #### The method of constructing a CU gate 
    #### by considering the U matriz of size 2x2, 
    #### the target qubit and the control qubit.
    #### when control qubit is more than target qubit 
    def gate_i_i2xn_inv(target_0,target_1,gate):
        left_part =  gates_basic.i() ## left part is initialized with an identity gate
        right_part = gates_basic.i() ## right part is initialized with an identity gate
                
        for j in range(target_0,target_1): ## iterative function to find the gates
                                           ## between target and controls qubits positions
            if j == target_1-1:            ## When find the Control qubit position we apply
                left_part = np.kron(left_part,gates_basic.p0x0())   ## apply the tensor product 
                right_part = np.kron(right_part,gates_basic.p1x1()) ## between left part and |0><0!
                                           ## and right_part with |1><1| and assign 
                                           ## in its respectively variable left_part or right part
                
            elif j == target_0:            ## When find the target qubit position we apply
                left_part = np.kron(gates_basic.i(),left_part) ## product tensor between left and
                right_part = np.kron(gate,right_part)          ## right part with  Identity and 
                                        ## U gate rrespectively
                    
            else:                       ## in other case apply on left_part and right_part
                left_part = np.kron(left_part,gates_basic.i())   ## the tensor product with
                right_part = np.kron(right_part,gates_basic.i()) ## identities gate of size 2x2
        
        O_state = left_part + right_part ## finally, adder the left_part matrix with right_part matrix
        return O_state                   ## return the final matrix 

#######################################################################
########## For the version 2:                                   #######
########## The gate_i_i2xn() and gate_i_i2xn_inv() methods      #######
#########$ can work in a single method under certain conditions #######
#######################################################################
    
    #### In case of having more than 3 qubits and the CU matrix is obtained, 
    #### within the simulator, the tensor product must be completed  
    #### in order to work correctly using the total_qubits,  
    #### the  CU matrix and the qubit's position of the target and control qubits
    def gate_moving(total_qubits,target_0,target_1,O_state):
        if target_1 == 0:                     ## When control qubit is in the position 0
            O_state = find_gate.gate_1xn(total_qubits-target_0,target_1,O_state) 
                                              ## consider 
                                              ## apply the same idea of tensor product 
                                              ## with a gate of sie 2x2
                        
        elif target_0 == total_qubits-1:      ## When target qubit is in the final qubit position
            O_state = find_gate.gate_1xn(target_1+1,target_1,O_state)
                                              ## apply the same idea of tensor product 
                                              ## with a gate of sie 2x2
                        
        elif target_1 != 0 and target_0 != total_qubits-1: ## when the gate is between 
                                              ## the first and last qubit
            O_state = find_gate.gate_1xn(total_qubits-target_0 + target_1,target_1,O_state)
                                              ## for identify the remaining qubits
        return O_state                        ## return the final matrix after the tensor product
    

In [10]:
########### gates_x.py  ##############################
#### The operators X and CX are defined         ###### 
#### and considering all the possibilities      ###### 
#### of being carried out from one qubit or     ######
#### two depending on the matrix up to N qubits ######
#### and may correspond to the expected result.  ######
######################################################

#### define the methods for the posibilities for X and CX
#### when have more qubits than 2.
#### using import numpy as np library for the matrices

class gates_x:
    # using u3 to define x gate where
    # theta = pi 
    # lamda = 0
    # phi = pi
    one_size = gates_basic.u3(np.pi,0,np.pi) # assign a variable x gate matrix
    
    cu_size =  np.array([[1, 0, 0, 0], # generate cx matrix
                      [0, 1, 0, 0],   # and assign a variable
                      [0, 0, 0, 1],   
                      [0, 0, 1, 0]])
    
    cu_inv_size = np.array([[1, 0, 0, 0], # matrices of 4x4 and higher 
                      [0, 0, 0, 1],     # need an inverse part that 
                      [0, 0, 1, 0],     # changes the order of their values
                      [0, 1, 0, 0]])


    def _1(self): # method when is X for a qubit in the simulation
        return gates_x.one_size # return the X gate matrix
    
    def _n(self,total_qubits,target): # method when there is more than one qubit 
                                      #and the X gate must be applied
        return find_gate.gate_1xn(total_qubits,target,gates_x.one_size)
                                      # return the tensor product 
    
    def cu(self): # method when is CX when control value is more bigger than target target
        return gates_x.cu_size # return cx matrix
    
    def cu_inv(self): # method when is CH when control value is more less than target target
        return gates_x.cu_inv_size # return the inverse of cx
    
    def cu_1xn(self,total_qubits,target): # method when is cx when control value is more bigger
                                          # than target by 1 and have 3 or more qubits 
                                          # in the quantum circuit
        return find_gate.gate_1xn(total_qubits,target,gates_x.cu_size) #return the tensor product
    
    def cu_1xn_inv(self,total_qubits,target): # method when is cx when control value is more bless
                                              # than target by 1 and have 3 or more qubits 
                                              # in the quantum circuit
        return find_gate.gate_1xn(total_qubits,target,gates_x.cu_inv_size) #return the tensor product
    
    def cu_i_i2xn(self,target_0,target_1):# method when is cx when control value is more bless
                                          # than target by more than 1 and have 3 or more qubits 
                                          # in the quantum circuit 
        return find_gate.gate_i_i2xn(target_0,target_1,gates_x.one_size)#return the tensor product
     
    def cu_i_i2xn_inv(self,target_0,target_1):# method when is cx when control value is more bless
                                              # than target by more than 1 and have 3 or more qubits 
                                              # in the quantum circuit
        return find_gate.gate_i_i2xn_inv(target_0,target_1,gates_x.one_size)#return the tensor product
        

In [11]:
########### gates_h.py  ##############################
#### The operators H and CH are defined         ###### 
#### and considering all the possibilities      ###### 
#### of being carried out from one qubit or     ######
#### two depending on the matrix up to N qubits ######
#### and may correspond to the expected result. ######
#### This class was added in the simulator to   ######
#### validate that the structure of the         ######
#### find_gate class can be used for any        ######
#### matrix u and cu.                           ######
######################################################

#### define the methods for the posibilities for H and CH
#### when have more qubits than 2.
#### using import numpy as np library for the matrices
class gates_h:
    # using u3 to define H gate where
    # theta = pi/2 
    # lamda = 0
    # phi = pi
    one_size = gates_basic.u3(np.pi/2,0,np.pi) # assign a variable H gate matrix
    
    cu_size =  np.array([[1, 0, 0, 0],# generate CH matrix
                      [0, 1, 0, 0],  #assign a variable
                      [0, 0, 1/np.sqrt(2), 1/np.sqrt(2)],
                      [0, 0, 1/np.sqrt(2), -1/np.sqrt(2)]])
    
    cu_inv_size = np.array([[1/np.sqrt(2), 1/np.sqrt(2), 0, 0], # matrices of 4x4 and higher 
                      [1/np.sqrt(2), -1/np.sqrt(2), 0, 0],      # need an inverse part that
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])

    def _1(self): # method when is H for a qubit in the simulation
        return gates_h.one_size # return the H gate matrix
    
    def _n(self,total_qubits,target): # method when there is more than one qubit 
                                      #and the H gate must be applied
        return find_gate.gate_1xn(total_qubits,target,gates_h.one_size) 
                                      # return the tensor product 

    def cu(self): # method when is CH when control value is more bigger than target target
        return gates_h.cu_size # return CH matrix
    
    def cu_inv(self): # method when is CH when control value is more less than target target
        return gates_h.cu_inv_size # return the inverse of CH
    
    def cu_1xn(self,total_qubits,target): # method when is CH when control value is more bigger
                                          # than target by 1 and have 3 or more qubits 
                                          # in the quantum circuit
        return find_gate.gate_1xn(total_qubits,target,gates_h.cu_size)#return the tensor product
    
    def cu_1xn_inv(self,total_qubits,target):# method when is CH when control value is more bless
                                              # than target by 1 and have 3 or more qubits 
                                              # in the quantum circuit
        return find_gate.gate_1xn(total_qubits,target,gates_h.cu_inv_size)#return the tensor product
    
    def cu_i_i2xn(self,target_0,target_1):# method when is CH when control value is more bless
                                          # than target by more than 1 and have 3 or more qubits 
                                          # in the quantum circuit 
        return find_gate.gate_i_i2xn(target_0,target_1,gates_h.one_size)#return the tensor product
     
    def cu_i_i2xn_inv(self,target_0,target_1):# method when is CH when control value is more bless
                                              # than target by more than 1 and have 3 or more qubits 
                                              # in the quantum circuit
        return find_gate.gate_i_i2xn_inv(target_0,target_1,gates_h.one_size)#return the tensor product

In [12]:
########### operator_size.py  ########################
#### The static class operator_size has two     ###### 
#### methods to identify the order of the       ###### 
#### output unitary matrix depending on the     ######
#### input qubits and targets.                  ######
######################################################

#### The methods aim to obtain the tensor product 
#### for gates of size 2x2 and 4x4 
#### when there are more than 1 or 2 qubits respectively.
class operator_size:

    def tam_1(total_qubits,target_0,gate): ## method for the two cases of a gate of size 2x2  
        if total_qubits == 1:              ## when has a qubit 
            O_state = gate._1()            ## return the original gate
        else:                              ## in other case  call gate._n to find the product tensor 
            O_state = gate._n(total_qubits, target_0) ## assign  in the output 
        return O_state                     ## and return the output matrix
    
    def tam_2(total_qubits,target_qubits,gate): ## method for all the cases of a gate of size 4x4 
        size_cu = total_qubits-1 ## how is gate 4x4 is necessary subtract 1 from the number of qubits
        if target_qubits[0] > target_qubits[1]: ## when control's qubit is more than target's qubit 
            if size_cu == 1:     ## case when have 2 qubis
                O_state = gate.cu()  ## apply direct the original gate
                
            elif target_qubits[0] - target_qubits[1] == 1: ## when the control's index is next to 
                                                ## with the target's index
                O_state = gate.cu_1xn(size_cu,target_qubits[1]) # apply the tensor product cu_1xn
                
            else:                    ## others case  we apply the method cu_i_i2xn
                O_state = gate.cu_i_i2xn(target_qubits[1],target_qubits[0])
                if O_state.shape[0] < 2**total_qubits: ## in case we need a bigger matrix
                    O_state = find_gate.gate_moving(total_qubits,target_qubits[0],## apply the method
                                                    target_qubits[1],O_state) ## gate_moving
        
        elif target_qubits[0] < target_qubits[1]: ## when control's qubit is less than target's qubit
            
            if size_cu == 1: ## case when have 2 qubis
                O_state = gate.cu_inv() ## apply direct the inverse original gate

            elif target_qubits[1] - target_qubits[0] == 1:## when the control's index is next to 
                                                ## with the target's index
                O_state = gate.cu_1xn_inv(size_cu,target_qubits[0]) # apply the tensor product cu_1xn
                
            else:                    ## others case  we apply the method cu_i_i2xn
                O_state = gate.cu_i_i2xn_inv(target_qubits[0],target_qubits[1])
                
                if O_state.shape[0] < 2**total_qubits: ## in case we need a bigger matrix
                    O_state = find_gate.gate_moving(total_qubits,target_qubits[1],## apply the method
                                                    target_qubits[0],O_state)  ## gate_moving 
            
        return O_state ## return the final matrix with the size 2**nx2**n with n = total_qubits

## Main functions for the simulation

In [13]:
########### task functios  ############################
#### The functions required to generate the      ###### 
#### simulator, which consists of generating the ###### 
#### initial state zero for N qubits, applying   ######
#### the gates to the input qubits, reading the  ######
#### quantum circuit and measuring               ######
#### the output qubits.                          ######
######################################################

#It is necessary to use the methods of the classes: 
# -gates_basic
# -find_gate
#and objects of type: 
# -gates_x 
# -gates_h
#Furthermore, is neccesary a exra module random
#for apply the weighted random.
import random #

# return vector of size 2**num_qubits with all zeroes except first element which is 1
def get_ground_state(num_qubits):
    vector = [0]* (2**num_qubits) # generar a vector of zeros with a sizeof 2^num_qubits
    vector[0] = 1 # modify the first element to 1
    return vector # return the vector result

# return unitary operator of size 2**n x 2**n for given gate and target qubits
def get_operator(total_qubits, gate_unitary, target_qubits, params):
    
    O_state = gates_basic.i() #the O_state variable of the output gate is
                              #initialized with the 2x2 identity matrix
    gate_list = ['h','x','u3','cx','ch'] # list of the unitary operators or quantum gatess
    
    if gate_unitary == gate_list[0]: # case h
        gate_i = gates_h() # an object of class gates_h is instantiated.
        O_state = operator_size.tam_1(total_qubits,target_qubits[0],gate_i) 
        #assign the matrix of size 2**nx2**n with the H gate in the target qubit position
            
    elif gate_unitary == gate_list[1]:# case x
        gate_i = gates_x() # an object of class gates_x is instantiated.
        O_state = operator_size.tam_1(total_qubits,target_qubits[0],gate_i)
        #assign the matrix of size 2**nx2**n with the X gate in the target qubit position
        
    elif gate_unitary == gate_list[2]: # case U3
        ## works similar with the method tam_! of class operator_size but don't exist
        ## the class U3 so work with the static method of fates_basic
        if total_qubits == 1:  ## when has a qubit, then return the original gate
            O_state = gates_basic.u3(params['theta'],params['lambda'],params['phi'])
        else:                  ## other case apply the tensor product with n-1 Identities gate
                               ## where n = total_qubits
            O_state = find_gate.gate_1xn(total_qubits,target_qubits[0],  ## assing U3 matrix to
                                         gates_basic.u3(params['theta'], ## variable O_state
                                                        params['lambda'],params['phi']))
        
    elif gate_unitary == gate_list[3]: ## case cx
        gate_i = gates_x() ## an object of class gates_x is instantiated.
        O_state = operator_size.tam_2(total_qubits,target_qubits,gate_i)
         #assign the matrix of size 2**nx2**n with the CX gate in the target qubit position

    elif gate_unitary == gate_list[4]: ## case ch
        gate_i = gates_h() ## an object of class gates_h is instantiated.
        O_state = operator_size.tam_2(total_qubits,target_qubits,gate_i)
         #assign the matrix of size 2**nx2**n with the CH gate in the target qubit position

    return O_state ## return the final matrix

def run_program(initial_state, program,global_params=None):
    # read program, and for each gate:
    #   - calculate matrix operator
    #   - multiply state with operator
    # return final state
    # code
    total_qubits = int(np.log2(len(initial_state))) #obtain the numbers of qubits 
    
    if global_params:  ## global parameters when work whit quantum variational circuits
        if len(global_params) == 2:
            global_params["lambda"] = -3.1415                      ##  deault value or the example
            global_params["theta"] = global_params.pop("global_1") ## global_1 params to theta
            global_params["phi"] = global_params.pop("global_2")   ## global:! params to phi
        for i in program: ## run the program
            matrix_unitary =  get_operator(total_qubits, i['gate'], i['target'],global_params)    
            initial_state = np.dot(matrix_unitary, initial_state) ## apply the dot product
    else:
        for i in program: ## run the program
            if 'params' in i: ## if exist params in the  input's data
                 ## get the input with params values 
                matrix_unitary =  get_operator(total_qubits, i['gate'], i['target'],i['params']) 
            else: ## in other case get the input's data without params values
                matrix_unitary =  get_operator(total_qubits, i['gate'], i['target'],None)

            initial_state = np.dot(matrix_unitary, initial_state) ## apply the dot product
                              ##  between the operator and the urrent vector state

    return initial_state # return the output_state after apply the unitary matrix with vector's input



    ## choose element from state_vector using weighted random and return it's index
def measure_all(state_vector):
    state_vector_output = []                ## list of the index of each output state
    state_vector_prob = []                  ## list of the scalar number of each output state 
    lenght = len(state_vector)              ## ientify the len of the state vector
    for i in range(lenght):                 ## and apply  a iterative function depend of the lenght
        index = bin(i)[2:]                  ## pass the integer value index to binary  number
        while len(index) < np.log2(lenght): ## in case to don't have the same lenght  we adder '0' 
            index = '0' + index             ## in the left part
        state_vector_output.append(str(index))              ## append the index binary value in a list
        state_vector_prob.append((abs(state_vector[i])**2)) ## append the probability value in a list 
                                                                    
    return random.choices(                  ## apply  choice which generate a weighted random
  population=state_vector_output,           ## list to the states  from the output
  weights=state_vector_prob,                ## weights/probabilities of the every state
  k=1)                                      ## apply random 1 time to find the output
  
    # simply execute measure_all in a loop num_shots times and
    # return object with statistics in following form:
    #   {
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      ...
    #   }
    # (only for elements which occoured - returned from measure_all)
def get_counts(state_vector, num_shots):
    measurment_dict = {}                          ## the dict output 
    for i in range(num_shots):                    ## apply a iterative function num_shots times
        index_dict = measure_all(state_vector)[0] ## obtain the measure_all result 
        
        if not index_dict in measurment_dict:     ## in case not exist the value in the dict
            measurment_dict[index_dict] = 1       ## we assign with 1 value
        else:                                     ## in other case
            measurment_dict[index_dict] += 1      ## increment the  index value with 1
    return measurment_dict                        ## finally return the dict output 
                                                  ## for all measurment


### Example usage

If your code is organized as we suggested, then usage will look like this:

In [14]:
# Define program:
my_circuit = [
{ "gate": "h", "target": [0] }, 
{ "gate": "cx", "target": [0, 1] } 
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(2)

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read results
counts = get_counts(final_state, 1000)

print(counts)
# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }
# Voila!

{'11': 503, '00': 497}


## Bonus requirements

If you have implemented simulator as described above: congratulations!

Now, if you wish you can continue improving it, first and useful thing to do would be to allow parametric gates:


### Parametric gates

For example, following gate:

```
[
  ["cos(theta/2)", "-exp(i * lambda) * sin(theta / 2)"],
  ["exp(i * phi) * sin(theta / 2)", "exp(i * lambda + i * phi) * cos(theta / 2)"]
]
```

Contains strings with expressions, and expressions can contain variables (usually angles in radians).

When your program gets gate like this, it should parse and evaluate expressions (with variables) and make a "normal" unitary matrix with values, which is then applied to the state vector.

Example program with parametric gates:

```
[
  { "unitary": [["cos(theta/2)", "-exp(i * lambda) * sin(theta / 2)"], ["exp(i * phi) * sin(theta / 2)", "exp(i * lambda + i * phi) * cos(theta / 2)"]], "params": { "theta": 3.1415, "phi": 1.15708, "lambda": -3.1415 }, "target": [0] }
  ...
]
```

Or, if you have defined unitaries somewhere in the program, then:

```
[
  { "gate": "u3", "params": { "theta": 3.1415, "phi": 1.5708, "lambda": -3.1415 }, "target": [0] }
  ...
]
```

Which your program translates to:

```
[
  [ 0+0j,  1+0j],
  [ 0+1j,  0+0j]
]
```


### Allow running variational quantum algorithms

With support for parametric gates, all you need to do is to allow global params - and your simulator will be able to run variational quantum algorithms!

In that case, parametrized gates in your program will contain strings instead parameter values:

```
[
  { "gate": "u3", "params": { "theta": "global_1", "phi": "global_2", "lambda": -3.1415 }, "target": [0] }
  ...
]
```

Notice `global_1` and `global_2` instead angle values, which you pass to `run_program` method:

```
final_state = run_program(my_qpu, my_circuit, { "global_1": 3.1415, "global_2": 1.5708 })
```

And that way you can use it in variational algorithms:

```
mu_qpu = [...]
my_circuit = [...]

def objective_function(params):
    final_state = run_program(my_qpu, my_circuit, { "global_1": params[0], "global_2": params[1] })

    counts = get_counts(final_state, 1000)
    
    # ...calculate cost here...
    
    return cost

# initial values
params = np.array([3.1415, 1.5708])

# minimize
minimum = minimize(objective_function, params, method="Powell", tol=1e-6)
```


### Parametric gates
example for the parametric gate

In [15]:
# Define program:
my_circuit = [
{ "gate": "u3", "params": { "theta": 3.1415, "phi": 1.5708, "lambda": -3.1415 }, "target": [0] }
]
# using y3 gate with the index params wiht theta, phi, lambda values

# Create "quantum computer" with 1 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(1)

print('Show the U3 gate  is equal to X gate') ## indicate that is an example of U3
print()

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read the final_state
print(final_state)

# Read results
counts = get_counts(final_state, 1000)
print(counts)

# Expect output
#[
#  [ 0+0j,  1+0j],
#  [ 0+1j,  0+0j]
#]

Show the U3 gate  is equal to X gate

[ 4.63267949e-05+0.j -3.67320510e-06+1.j]
{'1': 1000}


### Allow running variational quantum algorithms


In [16]:
from scipy.optimize import minimize ## need the mthod minimize of scipy.optimize module

my_qpu = get_ground_state(1)
my_circuit = [
{ "gate": "u3", "target": [0] }
    
]

real_value = np.random.randn(2,)    ## real_value

print("real number: ", real_value)


def calc_cost(real_value, circuit_value):
    diff = real_value - circuit_value       ## calculates the sum of squares 
    mod_abs = diff.real**2 + diff.imag**2   ## of mod of difference between corresponding elements 
    cost = np.sum(mod_abs)                  ## of real_value and circuit_value
    return cost                             ## returns the cost

def objective_function(params):            
    final_state = run_program(my_qpu, my_circuit, 
                              { "global_1": params[0], "global_2": params[1] })

    #counts = get_counts(final_state, 1000) ## return the values of the measure

    # ...calculate cost here...
    
    return calc_cost(real_value, final_state)

# initial values
params = np.array([3.1415, 1.5708])

# minimize
minimum = minimize(objective_function, params, method="Powell", tol=1e-6)
print(minimum)

real number:  [-0.24613536  0.17847547]
   direc: array([[-0.91538125,  0.45768459],
       [-0.02321982, -0.03266685]])
     fun: 0.484369964473336
 message: 'Optimization terminated successfully.'
    nfev: 127
     nit: 4
  status: 0
 success: True
       x: array([5.02842331e+00, 3.95805228e-08])


## Extra examples

Show different inputs and prove the result of the simulator

In [17]:
# Define program:
my_circuit = [
{ "gate": "h", "target": [0] }, 
{ "gate": "cx", "target": [0, 5] } 
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(6)

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read results
counts = get_counts(final_state, 1000)

print(counts)
# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }
# Voila!

{'100001': 479, '000000': 521}


In [18]:
# Define program:
my_circuit = [
{ "gate": "x", "target": [5] }, 
{ "gate": "cx", "target": [5, 0] } 
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(6)

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read results
counts = get_counts(final_state, 1000)

print(counts)
# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }
# Voila!

{'100001': 1000}


In [19]:
# Define program:
my_circuit = [
{ "gate": "h", "target": [0] }, 
{ "gate": "ch", "target": [0, 4] } 
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(6)

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read results
counts = get_counts(final_state, 1000)

print(counts)
# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }
# Voila!

{'000000': 489, '000001': 263, '010001': 248}


In [20]:
# Define program:
my_circuit = [
{ "gate": "x", "target": [2] }, 
{ "gate": "ch", "target": [2, 4] } 
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(6)

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read results
counts = get_counts(final_state, 1000)

print(counts)
# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }
# Voila!

{'010100': 505, '000100': 495}


In [21]:
# Define program:
my_circuit = [
{ "gate": "h", "target": [2] }, 
{ "gate": "cx", "target": [2, 3] } ,
{ "gate": "u3", "params": { "theta": 2.1415, "phi": 1.5708, "lambda": -3.1415 }, "target": [0] }
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = get_ground_state(6)

# Run circuit
final_state = run_program(my_qpu, my_circuit)

# Read results
counts = get_counts(final_state, 1000)

print(counts)
# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }
# Voila!

{'001101': 419, '000000': 115, '000001': 367, '001100': 99}


## Additional info/help

Any questions? Ping us on Slack!

To be blamed: Petar Korponaić,
Quantastica

May the force be with you!

## Next steps:

Implement ccx, swap, fredkin gate, works with swap test i nthe quantum variational circuits.
Also, I can do a better implementation of the classes and methods

## Final comments:

Very good task and with good activities, I hope to continue improving this project and that it can be a great simulator regardless of the result, I had a lot of fun making it and I think it can be improved, thank you very much for your resources.